### ISSUE TITLE
Support stdout

### ISSUE THREAD

**Issue by SleepyBag** [kaiwk/leetcode.el#18]
In leetcode, stdout of a program is shown in a frame which is different from the one used to show the returned value. e.g. When I put 'print' in python and test the code, the result of print will be shown in an output frame, even if my program finally gets a runtime error.
I think stdout very useful for debugging but it seems like that this function hasn't been implemented in this plugin. That is, at now, the stdout of my program doesn't show in emacs, although the same program does generate some output on the web version of leetcode. Hope this feature will be added.

**Comment by kaiwk** [comment]
I will add this soon : )
