### ISSUE TITLE
Spacemacs Layer

### ISSUE THREAD

**Issue by anmoljagetia** [kaiwk/leetcode.el#19]
Thank you for this package! It's beautiful. This is something that I had in mind but you beat me to it. I have an implementation of this ready but the keybindings are all messed up. I will fix all that I can but my Elisp foo isn't great. Would you be willing to help me on this journey - or even better - maintaining it?

**Comment by kaiwk** [comment]
Thank you! But I'm not sure I have time for this. Anyone is welcome to take it into spacemacs, it's how open source works : )

**Comment by anmoljagetia** [comment]
Sure, I will take this up in the coming few days.
Would appreciate if you could link it to my project once I have it ready.

**Comment by anmoljagetia** [comment]
So, I have created a nice spacemacs layer out of your package. Please find the link to it [here](https://github.com/anmoljagetia/leetcode-emacs-layer). I would appreciate it greatly if you could link to it and send some of the people who use your package and spacemacs my way so that I can improve on this first draft version that I have ready at the moment.

Thank you.
