### ISSUE TITLE
Feature: assign default code location and file name when saving

### ISSUE THREAD

**Issue by aladine** [kaiwk/leetcode.el#21]
As an user of both Leetcode plugin on VSCode and Emacs, I found there are many features could be implemented in Emacs: 
- Assign a default code location and file name when saving to the location
- Make leetcode login persistent as a session. It is already mentioned in https://github.com/kaiwk/leetcode.el/issues/15
- Change leetcode backend server via configuration. 
- Add problem description as the comment to the existing code.

Overall the current package looks great. Thanks for your effort to build this awesome package.

**Comment by kaiwk** [comment]
see #53
