### ISSUE TITLE
Symbol’s function definition is void: record

### ISSUE THREAD

**Issue by vicwer** [kaiwk/leetcode.el#45]
run `M-x leetcode`, then
```
aio-promise: Symbol’s function definition is void: record
```

**Comment by kaiwk** [comment]
`record` was added since Emacs 26.1, maybe you should upgrade your Emacs?

**Comment by vicwer** [comment]
ok, thank you!
BTW, is it work if I use leetcode-cn.com instead of leetcode.com?

**Comment by kaiwk** [comment]
I don't know, haven't test with `leetcode-cn.com` yet.
