### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by v2gt** [kaiwk/leetcode.el#46]
.emacs.d/elpa/leetcode-20191011.800/leetcode.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead. [8 times]
Contacting host: leetcode.com:443 [2 times]
LeetCode login failed: (error http 403)
Contacting host: leetcode.com:443

**Comment by kaiwk** [comment]
Now LeetCode uses reCAPTCHA. We can't login without recaptcha_token. I'm afraid they may add more login authentication from now on.

**Comment by kaiwk** [comment]
same problem here: https://github.com/skygragon/leetcode-cli/issues/196

**Comment by cole-jacobs** [comment]
So is there any workaround for this issue? I just installed this package today, and I'm having the same problem logging in.

**Comment by gopakumar** [comment]
> 
> 
> same problem here: [skygragon/leetcode-cli#196](https://github.com/skygragon/leetcode-cli/issues/196)

they fixed it using  login with cookie

**Comment by gopakumar** [comment]
is there any way to workaround it by using cookie

**Comment by yanzhang0219** [comment]
Any updates for this?

**Comment by kaiwk** [comment]
yes, It seems we can read chrome cookie from local directory and decrypt browser storage, so that we don't need login anymore.

https://github.com/skygragon/leetcode-cli-plugins/blob/master/plugins/cookie.chrome.js

I haven't look into it, but it maybe doable in Emacs too.

**Comment by yanzhang0219** [comment]
@kaiwk Thank you very much. Are you planning to implement that?

**Comment by kaiwk** [comment]
Sure

**Comment by yanzhang0219** [comment]
@kai wk

**Comment by kaiwk** [comment]
I fix this by using a [Python3 script](https://github.com/kaiwk/my_cookies) to decrypt Chrome cookies, since Emacs lisp lack crypto library such as PBKDF2.

some things should be aware of:
- before using this package, one should install the python package: `pip3 install my_cookies`
- before execute command `leetcode`, one need to login LeetCode in Chrome (Sorry, Firefox)
- currently, I only implement cookie decryption for Mac OSX

Hope someone can confirm it works on Mac, thank you!

**Comment by yanzhang0219** [comment]
That's awesome and the best news I got in this new year. I will give it a shot when I go back home later today. Thank you!!!!

**Comment by yanzhang0219** [comment]
Hello @kaiwk , I just tried it and I still could not log in. After executing M-x leetcode, there was a progress bar on the status bar and the progress bar kept moving from left to right, and nothing happened. I uploaded a [record](https://d.pr/v/CghYfz) for you to take a look. Thanks. 

By the way, my system is macOS 10.15.2.

**Comment by kaiwk** [comment]
> Hello @kaiwk , I just tried it and I still could not log in. After executing M-x leetcode, there was a progress bar on the status bar and the progress bar kept moving from left to right, and nothing happened. I uploaded a [record](https://d.pr/v/CghYfz) for you to take a look. Thanks.
> 
> By the way, my system is macOS 10.15.2.

Have you tried `my_cookie` in bash? It should ask for Mac OSX keychain password, after that it will print your `LEETCODE_SESSION` and `csrftoken`:

<img width="284" alt="屏幕快照 2020-01-02 下午8 42 28" src="https://user-images.githubusercontent.com/10190397/71667526-6e7e2700-2da0-11ea-8295-0a34d18bb170.png">

if it works, try to eval `(executable-find "my_cookies")`, it should return the path.

**Comment by yanzhang0219** [comment]
It works!!!!! Thank you very much.

**Comment by RicardoMing** [comment]
Any progress with Linux and Firefox support?
I found there is a python package, [browser_cookie3](https://github.com/borisbabic/browser_cookie3),  can extract cookies from web browsers with support for Chrome and Firefox on Linux, Mac and Windows.

**Comment by yiufung** [comment]
Seconded Linux and Firefox support. I tried with `browser_cookie3`, it's quite straight-forward to use and I can test it successfully under Linux/Firefox. It would be greatly appreciated if you may take a look and see if it's easy to integrate.

**Comment by kaiwk** [comment]
@RicardoMing @yiufung  I have update [my_cookies](https://pypi.org/project/my-cookies/), now it has [browser_cookie3](https://github.com/borisbabic/browser_cookie3) as dependency, you can upgrade it by `pip install --upgrade my_cookies`. make sure you use 0.1.1 version(it doesn't have `--version` flag though...), because if you use pypi mirror, it may not update yet.

**Comment by yiufung** [comment]
Works now with `my_cookies v0.1.1` and `leetcode v0.10.0`. Many thanks for the prompt update!

**Comment by codeofdusk** [comment]
I still get a `LeetCode fetch user and problems failed: (error connection-failed "connect" :host "leetcode.com" :service 443)`. Emacs can find the location of `my_cookies` (the eval worked) and `my_cookies` in terminal prints out my Leetcode session tokens. MacOS 10.15.2, Emacs 26.3.

**Comment by yanzhang0219** [comment]
@codeofdusk Try to close your Chrome completely by cmd-q and then restart the Chrome and login Leetcode again.

**Comment by codeofdusk** [comment]
Sadly still not working.

**Comment by yanzhang0219** [comment]
@codeofdusk Okay. On my side, it works very well. MacOS 10.15.2, GNU Emacs 26.3 (installed via "brew install emacs-plus")

**Comment by codeofdusk** [comment]
> @codeofdusk Okay. On my side, it works very well. MacOS 10.15.2, GNU Emacs 26.3 (installed via "brew install emacs-plus")

Got it working via a Linux VM with Firefox for login.

Thanks for making this – I'm totally blind and the Leetcode site doesn't read very well with my screen reader, but it works perfectly under tvraman/emacspeak.
