### ISSUE TITLE
Add to Melpa stable

### ISSUE THREAD

**Issue by isaprykin** [kaiwk/leetcode.el#47]
Hello!  This package looks great.

Could you please create a stable version and add it to Melpa stable?

I'm trying to maximize the stability of my emacs and I'm trying to use Melpa stable, so that the installed packages are not just HEAD version of github repos.  Thank you!

It seems like you just need to create a git tag for versions.

**Comment by kaiwk** [comment]
I have created a release, hope it works

**Comment by isaprykin** [comment]
It appears so!  https://stable.melpa.org/#/leetcode
Thank you, how awesome :-)
