### ISSUE TITLE
Cant leetcode-try nor leetcode-submit

### ISSUE THREAD

**Issue by roangel** [kaiwk/leetcode.el#48]
So, I tried your extension today. I think it's awesome! However, I have the following problem:

I successfully login and get the main problem list to load in emacs. As a test, I solved the `Two Sum` problem and tried to run it with `leetcode-try`, but got `LeetCode try failed: (error http 403) `. I tried with a different problem and it gives the same.

**Comment by roangel** [comment]
Trying to debug this I found out that if I remove all leetcode related cookies from chrome and start session with firefox, it works. 

I noticed that when using chrome (or brave browser) to sign in, the output of 'my_cookies' was a plain:
`LEETCODE_SESSION `
`csrftoken `

With firefox, however, it does print the entire tokens for both of them. Maybe there is an error in `my_cookies` side? Some unhandled exception?

**Comment by kaiwk** [comment]
> I noticed that when using chrome (or brave browser) to sign in

I think it's a problem of [browser_cookie3](https://github.com/borisbabic/browser_cookie3), since my_cookies is just a simple wrapper of it. Currently, browser_cookie3 only works with Firefox and Chrome, so it won't work with brave browser.
