### ISSUE TITLE
leetcode not success

### ISSUE THREAD

**Issue by vanniuner** [kaiwk/leetcode.el#63]
use M-x leetcode , out put is blew, and nothing next .
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: my_cookies in ./.local/lib/python3.6/site-packages (0.1.1)
Requirement already satisfied: browser-cookie3 in ./.local/lib/python3.6/site-packages (from my_cookies) (0.11.1)
Requirement already satisfied: lz4 in ./.local/lib/python3.6/site-packages (from browser-cookie3->my_cookies) (3.1.0)
Requirement already satisfied: pyaes in ./.local/lib/python3.6/site-packages (from browser-cookie3->my_cookies) (1.6.1)
Requirement already satisfied: pbkdf2 in ./.local/lib/python3.6/site-packages (from browser-cookie3->my_cookies) (1.3)
Requirement already satisfied: keyring in /usr/lib/python3/dist-packages (from browser-cookie3->my_cookies) (10.6.0)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.6/site-packages (from browser-cookie3->my_cookies) (3.9.8)
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from keyring->browser-cookie3->my_cookies) (2.3.1)

**Comment by kaiwk** [comment]
you are using system-provided python, try `sudo pip3 install my_cookies` in your terminal, then it should be ok.

**Comment by vanniuner** [comment]
on terminal emacs -nw it will be ok, but use gui emacs ,the out put is same .

**Comment by kaiwk** [comment]
`emacs -nw` works since it inherit from bash environment. To add bash environment manually in Emacs GUI, `C-h v` check `exec-path` value, and add the path to `my_cookies`.

Or you can use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) to add system PATH variable into Emacs.

**Comment by vanniuner** [comment]
(add-to-list 'exec-path "~/.local/lib/python3.6/site-packages/my_cookies/my_cookies.py")
this do not work ，please help

**Comment by kaiwk** [comment]
e.g. `which grep` gives `/usr/bin/grep`, you should add `/usr/bin/` to `exec-path`.

try `which my_cookies`, and do the same above.

**Comment by vanniuner** [comment]
it works

**Comment by oLd-Y** [comment]
> it works
 
Hey, are you still there? I'm having the same problem as you, but I'm using windows 11 and have no idea what' wrong. Which path did you end up taking to solve the problem, can you give me a reference?
