### ISSUE TITLE
Unable to fetch default Solution signature required for Leetcode problem in JAVA

### ISSUE THREAD

**Issue by abhijeetsrivastava** [kaiwk/leetcode.el#75]
I am unable to fetch default solution signature required for leetcode problem in JAVA. It downloads and shows the right signature for python program.

fyi, I am using DOOM Emacs.

`(use-package leetcode
  :config (setq leetcode-prefer-language "java"
                leetcode-prefer-sql "mysql"
                leetcode-save-solutions t))`

**Comment by kaiwk** [comment]
I'm afraid it's not the `leetcode.el`'s problem. Note that you need to restart(kill leetcode buffer, re-execute leetcode) after modified `leetcode-prefer-language`.
