### ISSUE TITLE
Enter Leetcode account and password manually

### ISSUE THREAD

**Issue by MatthewZMD** [kaiwk/leetcode.el#8]
I don't want to store my LeetCode account and password in my Emacs configuration file as my entire config is public on github. 
I also find it to be very troublesome to read the password from somewhere else.

```
(setq leetcode-account "your-account")
(setq leetcode-password "your-password")
```
Instead, I would like a prompt to enter it manually every time I start a leetcode client. Is it possible?

**Comment by kaiwk** [comment]
Now if you don't set `leetcode-account` and `leetcode-password`, a prompt will be given.
